### ISSUE TITLE
 InvalidIdentityPoolConfigurationException: Invalid identity pool configuration. Check assigned IAM roles for this pool.

### ISSUE THREAD

**Issue by rohitvinay** [awslabs/aws-serverless-auth-reference-app#29] opened 2017-06-18 05:57 UTC
I cloned the git repo, gulp deployed the aws settings, i get such an error loading the app
` Uncaught (in promise): InvalidIdentityPoolConfigurationException: Invalid identity pool configuration. Check assigned IAM roles for this pool.`

**Comment by justonian** [comment] 2017-08-06 23:39
Hmm. Did you run "gulp deploy" exact in the sequence provided in the developer guide? Also, have you manipulated the user pool or identity pool since it was programmatically created? I think that might have caused your issue here.

**Comment by justonian** [comment] 2017-09-12 06:33
Closing this issue since I've not been able to reproduce this issue and others have not reported it. I suggest completely un-deploying the project via gulp undeploy then re-deploying fresh as the issue above sounds like manual changes were made via the console which broke your deployment. A fresh deployment should fix this.

**Closed as completed by justonian** 2017-09-12 06:33 UTC
